[package]
name = "source-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

quick-xml = { version = "=0.36.1", features = ["serialize"] }
actix-web = { version = "4.0", features = [
    "rustls",
    "macros",
], default-features = false }
rusoto_core = { version = "0.47", default-features = false, features = [
    "rustls",
] }
rusoto_s3 = { version = "0.47", default-features = false, features = [
    "rustls",
] }
rusoto_dynamodb = { version = "0.47", default-features = false, features = [
    "rustls",
] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
xml-rs = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6"
bytes = "1.0"
serde_json = "1.0"
pin-project-lite = "0.2"
futures = "0.3"
log = "0.4"
env_logger = "0.9"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1.81"
serde_dynamodb = "0.9.0"
azure_storage_blobs = "0.20.0"
azure_storage = "0.20.0"
azure_core = "0.20.0"
time = { version = "0.3", features = ["formatting"] }
