[package]
name = "source-data-proxy"

version = "0.1.25"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

quick-xml = { version = "=0.36.1", features = ["serialize"] }
actix-web = { version = "^4", features = [
    "rustls",
    "macros",
], default-features = false }
rusoto_core = { version = "0.47", default-features = false, features = [
    "rustls",
] }
rusoto_s3 = { version = "0.47", default-features = false, features = [
    "rustls",
] }
rusoto_credential = { version = "0.47" }
tokio-util = { version = "0.7", features = ["codec"] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
xml-rs = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6"
bytes = "1.0"
pin-project-lite = "0.2"
futures = "0.3"
futures-core = "0.3"
log = "0.4"
env_logger = "0.9"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1.81"
azure_storage_blobs = "0.20.0"
azure_storage = "0.20.0"
azure_core = "0.20.0"
time = { version = "0.3", features = ["formatting"] }
url = "2.2.2"
reqwest = { version = "0.11.0", features = ["stream", "json"] }
actix-cors = "0.7.0"
moka = { version = "0.12.8", features = ["future"] }
percent-encoding = "2.1.0"
sha2 = "0.10.6"
hex = "0.4.3"
hmac = "0.12"
actix-http = "^3"
thiserror = "2.0.12"
