[package]
name = "source-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0"
rusoto_core = "0.47"
rusoto_s3 = "0.47"
rusoto_dynamodb = "0.47"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
xml-rs = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6"
bytes = "1.0"
serde_json = "1.0"
pin-project-lite = "0.2"
futures = "0.3"
log = "0.4"
env_logger = "0.9"
