compatibility_date = "2026-03-17"
main = "build/worker/shim.mjs"
workers_dev = true

[build]
command = "cargo install -q worker-build@0.7.5 && worker-build --release"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "source_data_proxy_staging"

[[services]]
binding = "LOCATION_WS"
service = "location_ws_staging"
