name = "location-ws"
main = "src/index.ts"
compatibility_date = "2026-03-17"

[[durable_objects.bindings]]
name = "LOCATION_HUB"
class_name = "LocationHub"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LocationHub"]

[vars]
MAX_BROADCASTS_PER_SECOND = "50"
CORS_ORIGIN = "*"
