name: Deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: development
  cancel-in-progress: false

jobs:


  deploy-cdk:
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: ./deploy
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.DEPLOY_ROLE_ARN }}
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ./deploy/package-lock.json
      - run: npm install -g aws-cdk
      - run: npm ci
      - name: Set vars to env
        env:
          VARS_JSON: ${{ toJSON(vars) }}
        run: |
          echo "$VARS_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV
      - run: cdk deploy --all --require-approval never
