name: Production

on:
  release:
    types: [published]

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy & Test
    needs: deploy-public-log-stream
    uses: ./.github/workflows/deploy.yml
    with:
      worker_name: source-data-proxy
      environment: production
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-public-log-stream:
    name: Deploy Public Log Stream
    uses: ./.github/workflows/deploy-public-log-stream.yml
    with:
      environment: production
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
