name: Staging

on:
  push:
    branches: [main]

concurrency:
  group: staging
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy & Test
    needs: deploy-location-ws
    uses: ./.github/workflows/deploy.yml
    with:
      wrangler_env: staging
      environment: staging
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-location-ws:
    name: Deploy Location WS
    uses: ./.github/workflows/deploy-location-ws.yml
    with:
      wrangler_env: staging
      environment: staging
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
